### ISSUE TITLE
Carl's Brown Bag

### ISSUE THREAD

**Issue by ono** [geckoboard/brownbags#2]
* Schedule: 2pm to 3pm on Friday, 16th January, 2015
* Speaker: @carlmw
* Subject: Living with other people's code

Leave a comment here if you plan to come so that we can know the rough number. We can also notify you in case we have to cancel the event in some reasons.

If you don't want to leave a comment, don't worry. You can also turn up at the time without a notice.

See [README](https://github.com/geckoboard/brownbags#venue) for the direction.

**Comment by stevebartholomew** [comment]
I'll be there!

**Comment by jgwhite** [comment]
I’ll be there!

**Comment by basicallydan** [comment]
I'll also be there!

**Comment by odub** [comment]
Planning to come, sounds good!

**Comment by basicallydan** [comment]
@carlmw Thank you very much for an excellent talk :) I found myself agreeing with you quite a lot on the subject, a subject close to my heart. Looks like Geckoboard's front end is in good hands. Well delivered too! :thumbsup:

@jgwhite Where should I email you? I know you showed me an email address but it just went straight through my brain without being committed to memory.

**Comment by leocassarani** [comment]
Thanks @carlmw, that was a definite success, and thanks to everyone who came and contributed to what I thought was a very good discussion.

For my part, here's the link to the Rands in Repose article I was thinking of: ["The QA Mindset"](http://randsinrepose.com/archives/the-qa-mindset/).

**Comment by jgwhite** [comment]
@basicallydan jamie@jgwhite.co.uk Thanks!

@carlmw great talk. Just been relaying the content to coworkers and it’s kicked off some extra discussions.

**Comment by stevebartholomew** [comment]
@carlmw I was nodding all the way through - really good talk :) Thanks for the invite @ono!

**Comment by ono** [comment]
Thanks guys for coming along! It was a really good meeting :clap: :clap: :clap:

Looking forward to the next one!

**Comment by carlmw** [comment]
Thanks for coming everyone. I put my slides on the web https://carlmw.github.io/livingwithcode/
